DROP TABLE if exists posts;
DROP TABLE if exists categories;
DROP TABLE if exists users;
DROP TABLE if exists votes;

CREATE TABLE posts (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  title VARCHAR(50) NOT NULL,
  content TEXT(255) NOT NULL,
  created_date DATETIME NOT NULL
);

CREATE TABLE categories (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nick VARCHAR(25) NOT NULL,
  email VARCHAR(89) NOT NULL,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE votes (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  post_id INT NOT NULL,
  name VARCHAR(50) NOT NULL
);



